server:
  port: 10080
spring:
  main:
    web-application-type: REACTIVE
  threads:
    virtual:
      enabled: true

---
spring:
  config:
    activate:
      on-profile: prod
logging:
  structured:
    format:
      console: ecs
    ecs:
      service:
        name: zombie-listener
