# syntax=docker/dockerfile:1
# Stage 1: Build
FROM maven:3.9.9-eclipse-temurin-21 AS build
WORKDIR /app

COPY pom.xml .
COPY avro-lib/pom.xml avro-lib/
COPY common/pom.xml common/
COPY core/pom.xml core/
COPY zombie-listener/pom.xml zombie-listener/
COPY gateway-server/pom.xml gateway-server/
COPY utils/pom.xml utils/

# 1. Cache dependencies
RUN --mount=type=cache,target=/root/.m2 \
    mvn dependency:go-offline -B -T 1C

# 2. Copy source
COPY . .

# 3. Build only gateway-server and its dependencies
RUN --mount=type=cache,target=/root/.m2 \
    mvn clean package -DskipTests -T 1C -pl :gateway-server -am

# Stage 2: Runtime
FROM eclipse-temurin:21-jre
WORKDIR /app

ADD https://repo1.maven.org/maven2/io/projectreactor/tools/blockhound/1.0.16.RELEASE/blockhound-1.0.16.RELEASE.jar blockhound.jar

COPY --from=build /app/gateway-server/target/gateway-server-*.jar app.jar

EXPOSE 9000

ENTRYPOINT ["java", "-XX:+AllowRedefinitionToAddDeleteMethods", "-javaagent:blockhound.jar", "-jar", "app.jar"]
