/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.devdooly.skeleton.avro.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class UserAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2190101128620772085L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"UserAvro\",\"namespace\":\"com.devdooly.skeleton.avro.schema\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"nameName\",\"type\":\"string\"},{\"name\":\"password\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<UserAvro> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<UserAvro> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<UserAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<UserAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<UserAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this UserAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a UserAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a UserAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static UserAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private long id;
  private java.lang.CharSequence nameName;
  private java.lang.CharSequence password;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public UserAvro() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param nameName The new value for nameName
   * @param password The new value for password
   */
  public UserAvro(java.lang.Long id, java.lang.CharSequence nameName, java.lang.CharSequence password) {
    this.id = id;
    this.nameName = nameName;
    this.password = password;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return nameName;
    case 2: return password;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: nameName = (java.lang.CharSequence)value$; break;
    case 2: password = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'nameName' field.
   * @return The value of the 'nameName' field.
   */
  public java.lang.CharSequence getNameName() {
    return nameName;
  }


  /**
   * Sets the value of the 'nameName' field.
   * @param value the value to set.
   */
  public void setNameName(java.lang.CharSequence value) {
    this.nameName = value;
  }

  /**
   * Gets the value of the 'password' field.
   * @return The value of the 'password' field.
   */
  public java.lang.CharSequence getPassword() {
    return password;
  }


  /**
   * Sets the value of the 'password' field.
   * @param value the value to set.
   */
  public void setPassword(java.lang.CharSequence value) {
    this.password = value;
  }

  /**
   * Creates a new UserAvro RecordBuilder.
   * @return A new UserAvro RecordBuilder
   */
  public static com.devdooly.skeleton.avro.schema.UserAvro.Builder newBuilder() {
    return new com.devdooly.skeleton.avro.schema.UserAvro.Builder();
  }

  /**
   * Creates a new UserAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new UserAvro RecordBuilder
   */
  public static com.devdooly.skeleton.avro.schema.UserAvro.Builder newBuilder(com.devdooly.skeleton.avro.schema.UserAvro.Builder other) {
    if (other == null) {
      return new com.devdooly.skeleton.avro.schema.UserAvro.Builder();
    } else {
      return new com.devdooly.skeleton.avro.schema.UserAvro.Builder(other);
    }
  }

  /**
   * Creates a new UserAvro RecordBuilder by copying an existing UserAvro instance.
   * @param other The existing instance to copy.
   * @return A new UserAvro RecordBuilder
   */
  public static com.devdooly.skeleton.avro.schema.UserAvro.Builder newBuilder(com.devdooly.skeleton.avro.schema.UserAvro other) {
    if (other == null) {
      return new com.devdooly.skeleton.avro.schema.UserAvro.Builder();
    } else {
      return new com.devdooly.skeleton.avro.schema.UserAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for UserAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<UserAvro>
    implements org.apache.avro.data.RecordBuilder<UserAvro> {

    private long id;
    private java.lang.CharSequence nameName;
    private java.lang.CharSequence password;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.devdooly.skeleton.avro.schema.UserAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.nameName)) {
        this.nameName = data().deepCopy(fields()[1].schema(), other.nameName);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.password)) {
        this.password = data().deepCopy(fields()[2].schema(), other.password);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing UserAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.devdooly.skeleton.avro.schema.UserAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.nameName)) {
        this.nameName = data().deepCopy(fields()[1].schema(), other.nameName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.password)) {
        this.password = data().deepCopy(fields()[2].schema(), other.password);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.devdooly.skeleton.avro.schema.UserAvro.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.devdooly.skeleton.avro.schema.UserAvro.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'nameName' field.
      * @return The value.
      */
    public java.lang.CharSequence getNameName() {
      return nameName;
    }


    /**
      * Sets the value of the 'nameName' field.
      * @param value The value of 'nameName'.
      * @return This builder.
      */
    public com.devdooly.skeleton.avro.schema.UserAvro.Builder setNameName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.nameName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'nameName' field has been set.
      * @return True if the 'nameName' field has been set, false otherwise.
      */
    public boolean hasNameName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'nameName' field.
      * @return This builder.
      */
    public com.devdooly.skeleton.avro.schema.UserAvro.Builder clearNameName() {
      nameName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'password' field.
      * @return The value.
      */
    public java.lang.CharSequence getPassword() {
      return password;
    }


    /**
      * Sets the value of the 'password' field.
      * @param value The value of 'password'.
      * @return This builder.
      */
    public com.devdooly.skeleton.avro.schema.UserAvro.Builder setPassword(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.password = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'password' field has been set.
      * @return True if the 'password' field has been set, false otherwise.
      */
    public boolean hasPassword() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'password' field.
      * @return This builder.
      */
    public com.devdooly.skeleton.avro.schema.UserAvro.Builder clearPassword() {
      password = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public UserAvro build() {
      try {
        UserAvro record = new UserAvro();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.nameName = fieldSetFlags()[1] ? this.nameName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.password = fieldSetFlags()[2] ? this.password : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<UserAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<UserAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<UserAvro>
    READER$ = (org.apache.avro.io.DatumReader<UserAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.id);

    out.writeString(this.nameName);

    out.writeString(this.password);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readLong();

      this.nameName = in.readString(this.nameName instanceof Utf8 ? (Utf8)this.nameName : null);

      this.password = in.readString(this.password instanceof Utf8 ? (Utf8)this.password : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readLong();
          break;

        case 1:
          this.nameName = in.readString(this.nameName instanceof Utf8 ? (Utf8)this.nameName : null);
          break;

        case 2:
          this.password = in.readString(this.password instanceof Utf8 ? (Utf8)this.password : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










