skeleton.datasource.jdbc.driver-class-name=org.h2.Driver
skeleton.datasource.jdbc.pool-name=pool1
skeleton.datasource.jdbc.username=sa
skeleton.datasource.jdbc.password=
skeleton.datasource.jdbc.jdbc-url=jdbc:h2:mem:skeleton;MODE=MySQL;DB_CLOSE_DELAY=-1
skeleton.datasource.jdbc.maximum-pool-size=10
skeleton.datasource.jdbc.minimum-idle=1
skeleton.datasource.jdbc.connection-timeout=20000
skeleton.datasource.jdbc.validation-timeout=5000
skeleton.datasource.jdbc.idle-timeout=200000
skeleton.datasource.jdbc.max-lifetime=300000

skeleton.kafka.bootstrap-servers[0]=localhost:9092
skeleton.kafka.key-serializer=org.apache.kafka.common.serialization.StringSerializer
skeleton.kafka.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
skeleton.kafka.value-serializer=org.apache.kafka.common.serialization.StringSerializer
skeleton.kafka.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
skeleton.kafka.schema-registry-url=http://localhost:8081
